const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),engine=require('web-audio-engine');
const NBS=require('../web/nbs.js');
function context(){const scope={NBS,AudioContext:engine.RenderingAudioContext,OfflineAudioContext:engine.OfflineAudioContext,atob,Uint8Array,Blob,DataView,ArrayBuffer,setInterval,clearInterval};scope.globalThis=scope;vm.runInNewContext(fs.readFileSync(require.resolve('../web/audio.js'),'utf8'),scope);return scope.NBSAudio;}
function song(){return {vanilla:16,customs:[],duration:1,tempo:50,layers:[{volume:50,pan:100},{volume:25,pan:100}],notes:[{time:.1,tick:5,instrument:0,key:45,velocity:20,pan:100,fine:0,layer:0},{time:.5,tick:25,instrument:0,key:45,velocity:100,pan:100,fine:0,layer:1}]};}
async function make(){const audio=context(),p=new audio.Player();await p.contextReady();const buffer=p.context.createBuffer(1,4410,44100);buffer.getChannelData(0).fill(.5);p.bank.set(0,buffer);p.setSong(song());return {p,audio};}
test('offline mix preserves layer gain, selected layers and fixed decay',async()=>{const {p,audio}=await make();const full=await p.render();p.predicate=n=>n.layer===0;const solo=await p.render();assert.ok(full.peak>.17&&full.peak<.18);assert.equal(full.peak,solo.peak);assert.equal(solo.buffer.getChannelData(0)[25000],0);assert.ok(full.buffer.getChannelData(0)[25000]>0);const blob=audio.wav(solo.buffer);assert.equal(blob.size,44+solo.buffer.length*4);});
test('full NBS velocity differs from layer-only game profile',async()=>{const {p}=await make();p.predicate=n=>n.layer===0;const a=await p.render();p.profile='nbs';const b=await p.render();assert.ok(Math.abs(b.peak/a.peak-.2)<1e-6);});
test('missing samples fail explicitly and clipping is detected',async()=>{const {p}=await make();p.bank.clear();await assert.rejects(()=>p.render(),/Missing samples/);const buffer=p.context.createBuffer(1,4410,44100);buffer.getChannelData(0).fill(1);p.bank.set(0,buffer);p.song.notes=Array.from({length:8},()=>({...p.song.notes[0]}));const out=await p.render();assert.ok(out.clipped>0);assert.ok(out.peak>1);});
test('seeking and song switch preserve requested absolute time',async()=>{const {p}=await make();await p.seek(.6);assert.equal(p.current(),.6);p.setSong(song(),true);assert.equal(p.current(),.6);p.setSong(song());assert.equal(p.current(),0);});
